Blacklist: []

Binance_Example:
  key: replace_with_binance_api_key
  secret: replace_with_binance_secret_key
  initial_unit: 1000000
  principal: 1000000
  account_type: account
  exchange: Binance
  interest_rate: 0
  client: ExampleClient
  ccy: USDT
  # skip_default_feishu: true # 可选，跳过飞书群发送

Gate_Example:
  key: replace_with_gate_api_key
  secret: replace_with_gate_secret_key
  initial_unit: 1000000
  principal: 1000000
  account_type: account
  exchange: Gate
  interest_rate: 0
  client: ExampleClient
  ccy: USDT
  # skip_default_feishu: true # 可选，跳过飞书群发送

KuCoin_Example:
  key: replace_with_kucoin_api_key
  secret: replace_with_kucoin_api_secret
  passphrase: replace_with_kucoin_api_passphrase
  initial_unit: 1000000
  principal: 1000000
  account_type: account
  exchange: KuCoin
  interest_rate: 0
  client: ExampleClient
  ccy: USDT
  # skip_default_feishu: true # 可选，跳过飞书群发送

OKX_Example:
  key: replace_with_okx_api_key
  secret: replace_with_okx_api_secret
  passphrase: replace_with_okx_api_passphrase
  initial_unit: 1000000
  principal: 1000000
  account_type: account
  exchange: OKX
  interest_rate: 0
  client: ExampleClient
  ccy: USDT
  # skip_default_feishu: true # 可选，跳过飞书群发送
